In [21]:
def Capture(NO,Train,d):


    import os
    import cv2
    import numpy as np

    os.system('rm -rf ./model/Train/*')
    os.system('rm -rf ./model/Test/*')
    os.system('mkdir ./model ./model/Train')
    os.system('mkdir ./model ./model/Test')

    name 
    for i in range(NO):
        print("Start for ",i+1)
    

# Load HAAR face classifier
        face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load functions
        def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
            gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            faces = face_classifier.detectMultiScale(gray, 1.3, 5)
            print(faces)
            if faces is ():
                return None
    
    
    
    
    
    
    # Crop all faces found
            for (x,y,w,h) in faces:
                cropped_face = img[y:y+h, x:x+w]

            return cropped_face

# Initialize Webcam

        cap = cv2.VideoCapture(0)
        count = 0

# Collect 100 samples of your face from webcam input
        while True:

            ret, frame = cap.read()
            if face_extractor(frame) is not None:
                count += 1
                face = cv2.resize(face_extractor(frame), (300, 300))

        # Save file in specified directory with unique name
                
                os.system('mkdir ./model/'+d+'/n'+str(i))
                file_name_path = './model/'+d+'/n'+str(i)+'/' + str(count) + '.jpg'
                cv2.imwrite(file_name_path, face)

        # Put count on images and display live count
                cv2.imshow('Face Cropper', face)
                cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)

        
            else:
                print("Face not found")
                pass

            if cv2.waitKey(1) == 13 or count == Train: #13 is the Enter Key
                break
        
        cap.release()
        cv2.destroyAllWindows()      
        print("Collecting Samples Complete")
        input("Press enter for next object ")

In [22]:
datatype  = int(input("Enter 1 for Train data  or 2 for Test data : " ))
if datatype ==1:
    NO = int(input("Enter Number of person :  "))
    Train = int(input("How much photo you want to take : "))
    Capture(NO,Train,"Train")
elif datatype ==2:
    NO = int(input("Enter Number of person :  "))
    Train = int(input("How much photo you want to take : "))
    Capture(NO,Train,"Test")
else:
    print("Enter valid number")
    exit(0)

Enter 1 for Train data  or 2 for Test data :  1
Enter Number of person :   5
How much photo you want to take :  10


Start for  1
[[200 172 267 267]]
[[200 172 267 267]]
[[203 176 262 262]]
[[203 176 262 262]]
[[204 173 268 268]]
[[204 173 268 268]]
[[203 172 267 267]]
[[203 172 267 267]]
[[204 176 265 265]]
[[204 176 265 265]]
[[206 174 264 264]]
[[206 174 264 264]]
[[205 176 261 261]]
[[205 176 261 261]]
[[208 178 258 258]]
[[208 178 258 258]]
[[210 180 256 256]]
[[210 180 256 256]]
[[205 176 264 264]]
[[205 176 264 264]]


Press enter for next object  


Start for  2
[[213 157 255 255]]
[[213 157 255 255]]
[[219 163 243 243]]
[[219 163 243 243]]
[[220 162 242 242]]
[[220 162 242 242]]
[[222 163 238 238]]
[[222 163 238 238]]
[[216 157 253 253]]
[[216 157 253 253]]
[[220 158 248 248]]
[[220 158 248 248]]
[[218 156 253 253]]
[[218 156 253 253]]
[[211 151 262 262]]
[[211 151 262 262]]
[[213 150 261 261]]
[[213 150 261 261]]
[[216 151 259 259]]
[[216 151 259 259]]


Press enter for next object  


Start for  3
[[216 153 259 259]]
[[216 153 259 259]]
[[217 155 257 257]]
[[217 155 257 257]]
[[218 154 257 257]]
[[218 154 257 257]]
[[217 156 257 257]]
[[217 156 257 257]]
[[218 156 251 251]]
[[218 156 251 251]]
[[223 159 245 245]]
[[223 159 245 245]]
[[216 152 256 256]]
[[216 152 256 256]]
[[215 150 262 262]]
[[215 150 262 262]]
[[212 152 262 262]]
[[212 152 262 262]]
[[213 150 266 266]]
[[213 150 266 266]]


Press enter for next object  


Start for  4
[[223 160 248 248]]
[[223 160 248 248]]
[[221 161 247 247]]
[[221 161 247 247]]
[[222 163 245 245]]
[[222 163 245 245]]
[[219 158 255 255]]
[[219 158 255 255]]
[[222 162 245 245]]
[[222 162 245 245]]
[[225 164 243 243]]
[[225 164 243 243]]
[[222 161 247 247]]
[[222 161 247 247]]
[[221 161 248 248]]
[[221 161 248 248]]
[[219 157 253 253]]
[[219 157 253 253]]
[[224 162 241 241]]
[[224 162 241 241]]


Press enter for next object  


Start for  5
[[218 162 252 252]]
[[218 162 252 252]]
[[219 163 250 250]]
[[219 163 250 250]]
[[216 163 254 254]]
[[216 163 254 254]]
[[217 160 256 256]]
[[217 160 256 256]]
[[216 162 255 255]]
[[216 162 255 255]]
[[217 163 259 259]]
[[217 163 259 259]]
[[213 158 266 266]]
[[213 158 266 266]]
[[211 165 262 262]]
[[211 165 262 262]]
[[206 163 268 268]]
[[206 163 268 268]]
[[208 164 262 262]]
[[208 164 262 262]]


Press enter for next object  
