In [1]:
import os
import cv2
import numpy as np
datatype  = int(input("Enter 1 for Train data  or 2 for Test data"))
os.system('rm -rf ./model/Train/*')
os.system('rm -rf ./model/Test/*')

if datatype == 1:
    NO = int(input("Enter your object no."))
    Train = int(input("How much photo no"))
    for i in range(NO):
        print("Start for ",i+1)
    

# Load HAAR face classifier
        face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load functions
        def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
            gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            faces = face_classifier.detectMultiScale(gray, 1.3, 5)
            print(faces)
            if faces is ():
                return None
    
    
    
    
    
    
    # Crop all faces found
            for (x,y,w,h) in faces:
                cropped_face = img[y:y+h, x:x+w]

            return cropped_face

# Initialize Webcam

        cap = cv2.VideoCapture(0)
        count = 0

# Collect 100 samples of your face from webcam input
        while True:

            ret, frame = cap.read()
            if face_extractor(frame) is not None:
                count += 1
                face = cv2.resize(face_extractor(frame), (300, 300))

        # Save file in specified directory with unique name
                
                os.system('mkdir ./model/Train/n'+str(i))
                file_name_path = './model/Train/n'+str(i)+'/' + str(count) + '.jpg'
                cv2.imwrite(file_name_path, face)

        # Put count on images and display live count
                cv2.imshow('Face Cropper', face)
                cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)

        
            else:
                print("Face not found")
                pass

            if cv2.waitKey(1) == 13 or count == Train: #13 is the Enter Key
                break
        
        cap.release()
        cv2.destroyAllWindows()      
        print("Collecting Samples Complete")
        input("Press enter for next object ")
elif datatype ==2:
    NO = int(input("Enter your object no."))
    Test = int(input("How much photo no"))
    for i in range(NO):
        print("Start for ",i+1)
    

# Load HAAR face classifier
        face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load functions
        def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
            gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            faces = face_classifier.detectMultiScale(gray, 1.3, 5)
            print(faces)
            if faces is ():
                return None
    
    # Crop all faces found
            for (x,y,w,h) in faces:
                cropped_face = img[y:y+h, x:x+w]

            return cropped_face

# Initialize Webcam

        cap = cv2.VideoCapture(0)
        count = 0

# Collect 100 samples of your face from webcam input
        while True:

            ret, frame = cap.read()
            if face_extractor(frame) is not None:
                count += 1
                face = cv2.resize(face_extractor(frame), (300, 300))

        # Save file in specified directory with unique name

                os.system('mkdir ./model/Test/n'+str(i))
                file_name_path = './model/Test/n'+str(i)+'/' + str(count) + '.jpg'
                cv2.imwrite(file_name_path, face)

        # Put count on images and display live count
                cv2.imshow('Face Cropper', face)
                cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)

        
            else:
                print("Face not found")
                pass

            if cv2.waitKey(1) == 13 or count == Test: #13 is the Enter Key
                break
      
        cap.release()
        cv2.destroyAllWindows()      
        print("Collecting Samples Complete")
        input("Press enter for next object ")
else:
    print("plz enter valid number")
    exit(0)

Enter 1 for Train data  or 2 for Test data 1
Enter your object no. 2
How much photo no 3


Start for  1
[[233 238 218 218]]
[[233 238 218 218]]
[[232 231 223 223]]
[[232 231 223 223]]
[[230 221 224 224]]
[[230 221 224 224]]


Press enter for next object  


Start for  2
[[239 208 226 226]]
[[239 208 226 226]]
[[240 210 224 224]]
[[240 210 224 224]]
[[241 210 223 223]]
[[241 210 223 223]]


Press enter for next object  


Enter valid number
