In [1]:
NO = int(input("Enter your object no."))
Train = int(input("How much photo no"))
import os
for i in range(NO):
    print("Start for ",i+1)
    import cv2
    import numpy as np

# Load HAAR face classifier
    face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load functions
    def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5)
        print(faces)
        if faces is ():
            return None
    
    # Crop all faces found
        for (x,y,w,h) in faces:
            cropped_face = img[y:y+h, x:x+w]

        return cropped_face

# Initialize Webcam

    cap = cv2.VideoCapture(0)
    count = 0

# Collect 100 samples of your face from webcam input
    while True:

        ret, frame = cap.read()
        if face_extractor(frame) is not None:
            count += 1
            face = cv2.resize(face_extractor(frame), (300, 300))

        # Save file in specified directory with unique name
            os.system('mkdir ./model/Train/n'+str(i))
            file_name_path = './model/Train/n'+str(i)+'/' + str(count) + '.jpg'
            cv2.imwrite(file_name_path, face)

        # Put count on images and display live count
            cv2.imshow('Face Cropper', face)
            cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)

        
        else:
            print("Face not found")
            pass

        if cv2.waitKey(1) == 13 or count == 5: #13 is the Enter Key
            break
        
    cap.release()
    cv2.destroyAllWindows()      
    print("Collecting Samples Complete")
    input("Press enter for next object ")

enter your object no. 5


Start for  1
[[229 183 233 233]]
[[229 183 233 233]]
[[228 181 236 236]]
[[228 181 236 236]]
[[229 184 233 233]]
[[229 184 233 233]]
[[231 185 233 233]]
[[231 185 233 233]]
[[229 182 234 234]]
[[229 182 234 234]]


Enter for second object  5


Start for  2
[[233 179 227 227]]
[[233 179 227 227]]
[[231 178 229 229]]
[[231 178 229 229]]
[[229 178 231 231]]
[[229 178 231 231]]
[[228 180 231 231]]
[[228 180 231 231]]
[[231 182 224 224]]
[[231 182 224 224]]


Enter for second object  5


Start for  3
[[225 185 224 224]]
[[225 185 224 224]]
[[220 183 232 232]]
[[220 183 232 232]]
[[223 186 225 225]]
[[223 186 225 225]]
[[220 178 236 236]]
[[220 178 236 236]]
[[219 177 238 238]]
[[219 177 238 238]]


Enter for second object  5


Start for  4
[[219 177 240 240]]
[[219 177 240 240]]
[[221 177 238 238]]
[[221 177 238 238]]
[[219 177 242 242]]
[[219 177 242 242]]
[[221 180 237 237]]
[[221 180 237 237]]
[[223 180 237 237]]
[[223 180 237 237]]


Enter for second object  5


Start for  5
[[223 189 229 229]]
[[223 189 229 229]]
[[221 187 233 233]]
[[221 187 233 233]]
[[223 188 231 231]]
[[223 188 231 231]]
[[224 191 229 229]]
[[224 191 229 229]]
[[218 185 240 240]]
[[218 185 240 240]]


Enter for second object  5
